import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

import { Input, FormControl, Button, FormLabel } from "@chakra-ui/react";
import { FormEvent } from "react";

export default function Home() {
  const router = useRouter();
  const formHandler = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const name = e.target[0].value;

    if (!name) return;

    //TODO Valider le nom pour etre sur d'avoir quelque chose de bon

    router.push("/summoner/[name]", `/summoner/${name}`);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>LoL Info</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to LoL Info</h1>

        <form onSubmit={(e) => formHandler(e)}>
          <FormControl isRequired>
            <FormLabel>Summoner's name</FormLabel>
            <Input placeholder="Yassuo" />
          </FormControl>

          <Button width="full" mt={4} colorScheme="teal" type="submit">
            Search
          </Button>
        </form>
      </main>
    </div>
  );
}
